---
title: "seafood"
author: "Alan Nurcahyo"
date: "9/5/2020"
output: pdf_document
---

```{r message=FALSE}
#library used
library(tidyverse)
library(caret)
library(quanteda)
library(doSNOW) #run model to run in each core
library(cld3)
library(googleLanguageR)
library(irlba)
```

# Preprocessing
## Load and review dataset
```{r}
#load dataset
df <- read_csv("/Users/alannurcahyo/Documents/Documents/AU/fall2020/DATA/Seafood_Dishes.csv")
unique(df$seafood_yn) ##check label
df.labeled <- df%>%
  select(-description) %>%
  filter(seafood_yn %in% c(0,1))

prop.table(table(df.labeled$seafood_yn))
```

Translate
```{r}
#detect langauage -- cld3 
df.labeled.cld3 <- df.labeled%>%
  mutate(name = str_to_lower(name),
         lang = cld3::detect_language(name))
df.labeled.cld3 %>%
  filter(lang == "en")

# estimate cost we use Google API?
df.labeled.count <- df.labeled%>%
  mutate(text.length = nchar(name))
estimated.cost <- sum(df.labeled.count$text.length)/500000*20 #for labeled data only, per call
```


```{r}

## use google API
gl_auth("seafood-translation-f329aa685c7f.json")
df.name.translate <- vector(mode = "list", length = nrow(df.labeled))

for (i in seq_along(df.name.translate)) {
     df.name.translate[[i]] <- gl_translate(df.labeled$name[i], target = "en")
}

df.name.translate.bind <- do.call(rbind, df.name.translate)
prop.table(table(df.name.translate.bind$detectedSourceLanguage))

write.csv(df.name.translate.bind,"NameTranslated.csv")
df.name.translate.bind <- read_csv("NameTranslated.csv")

##use translated as our dataset
df.labeled <- cbind(df.labeled, df.name.translate.bind)
df.labeled <- df.labeled %>%
  select(-text) %>%
  select(-X1)
head(df.labeled)


## Comparation between cld3 and GoogleAPI  -- googleAPI is outperform cld3 in language detection

df.name.translate.bind %>%
  group_by(detectedSourceLanguage) %>%
  tally() %>%
  arrange(desc(n)) %>%
  mutate(prop = n/nrow(df.name.translate.bind)) %>%
  slice(1:5) %>%
  ggplot(aes(detectedSourceLanguage,prop)) + geom_col() +
  theme_bw() + labs(title = "top 5 language by google")

df.labeled.cld3 %>%
  group_by(lang) %>%
  tally() %>%
  arrange(desc(n)) %>%
  mutate(prop = n/nrow(df.name.translate.bind)) %>%
  slice(1:5) %>%
  ggplot(aes(lang,prop)) + geom_col() +
  theme_bw() + labs(title = "top 5 language by cld3")

head(df.labeled)
```

# create training and test

```{r}
set.seed(1234)

#create index of stratified 70:30 split that maintain proportion of label.
index <- caret::createDataPartition(df.labeled$seafood_yn, times = 1,
                                    p = 0.7, list= FALSE) 

# train and test
train <- df.labeled[index,]
test <- df.labeled[-index,]

##verify
prop.table(table(train$seafood_yn))
prop.table(table(test$seafood_yn))
```


## preprocess train
```{r}
corpus <- corpus(train$translatedText) #create a corpus


#create document frequency matrix in a go
dfm.train <- dfm(corpus, 
             tolower=TRUE,  
             remove_punct =TRUE, 
             remove_numbers=TRUE,
             remove_symbols = TRUE,
             remove_hyphens = TRUE,
             remove=stopwords('english', source = "snowball"), 
             stem=TRUE, 
             verbose=TRUE)

view(dfm.train[1:20,1:100])


## Make syntactically valid column names out of character vectors.
names(train.token) <- make.names(names(train.token))
train.token <- train.token[-2]

############## make TF-IDF version of data
## make tf function
term.frequency <- function(row){
  row/sum(row)
}

## make function to calculate IDF
inverse.doc.freq <- function(col) {
  corpus.size <- length(col)
  doc.count <- length(which(col>0))
  log10(corpus.size/doc.count)
}

## make function to calculate tf/idf

tf.idf <- function(tf,idf) {
  tf*idf
}

## make tf matrix transformation 
dfm.train.tf <- apply(dfm.train, 1, term.frequency)
dim(dfm.train)

## make idf . This IDF will be used again later in test dataset
dfm.train.idf <- apply(dfm.train, 2, inverse.doc.freq)

## make tf-idf matrix 
dfm.train.tfidf <- apply(dfm.train.tf, 2, tf.idf, idf = dfm.train.idf)
dim(dfm.train.tfidf)

## transpose t-idf matrix
dfm.train.tfidf <- t(dfm.train.tfidf)
dim(dfm.train.tfidf)
view(dfm.train.tfidf[1:20,1:100])

## check incomplete cases
incomplete.cases <- which(!complete.cases(dfm.train.tfidf))
train$translatedText[incomplete.cases]

## fix it
dfm.train.tfidf[incomplete.cases,] <- rep(0.0, ncol(dfm.train.tfidf))

###### end of tf-idf ########


########## Singular value decomposition ##########

## record start time
start.time <- Sys.time()

### perform SVD to decrease dimentionality  to 300 using package irlba
train.irlba <- irlba(t(dfm.train.tfidf), nv = 300, maxit = 600)

## total time ~12 minutes
total.time <- Sys.time() - start.time 


## save svd value for test data
sigma.inverse <- 1/train.irlba$d
u.transpose <- t(train.irlba$u)

##setup feature dataframe with label
train.svd <- data.frame(label=as.factor(train$seafood_yn), train.irlba$v)
dim(train.svd)
```

# make models use only names 
## use R default setting - Error: protect(): protection stack overflow 
## - try to tweak default R setting: Error: vector memory exhausted (limit reached?)
## solution to try: 1. use feature selection to decrease variable 2. use GPU Cloud? 
```{r}
set.seed(1234)
# use caret package to make stratified 10-fold cross validation repeated

cv.folds <- createMultiFolds(train$seafood_yn, k = 10, times = 1)
cv.control <- trainControl(method = "repeatedcv", number = 10,
                           repeats = 1, index = cv.folds)

# time the code execution
start.time <- Sys.time()

#create cluster to work on 2 cores using doSNOW package to cut time execution
cl <- makeCluster(2, type="SOCK")
registerDoSNOW(cl)

# build decision tree - rpart
rpart.cv.1 <- train(label~.,data = train.svd, 
                    method = "rf",
                    trcontrol = cv.control,
                    tuneLength = 3)
# when processing is done, stop cluster
stopCluster(cl)

total.time <- Sys.time() - start.time
```


